-- create table
CREATE TABLE treinamento_sql (col1 number,
col2 varchar2(100),
col3 varchar2(100) NOT NULL,
CONSTRAINT chave_primaria_pk PRIMARY KEY (col1));

CREATE TABLE treinamento_sql2 (col1 number,
col2 varchar2(100),
col3 varchar2(100) NOT NULL,
CONSTRAINT chave_estrangeira_fk FOREIGN KEY (col1) REFERENCES treinamento_sql(col1));

DROP TABLE treinamento_sql;

DROP TABLE treinamento_sql2;


-- create index
CREATE INDEX IDX_treinamento_sql_col2 ON treinamento_sql (col2);

DROP INDEX IDX_treinamento_sql_col2;

SELECT * FROM treinamento_sql WHERE col2 = 'teste';

SELECT * FROM treinamento_sql WHERE upper(col2) = 'teste';


-- teste index
SELECT * FROM treinamento_sql;

-- insert
INSERT INTO treinamento_sql VALUES (2, 'col2_1', 'col3_1');

-- Update
UPDATE treinamento_sql SET col2 = 'col2_1_atualizado', col3 = 'col3_1_atualizado' WHERE col1 = 1;

-- Delete
DELETE FROM treinamento_sql WHERE col1 = 1;

-- SELECT SIMPLES
SELECT * FROM SUBSCRIPTION s;

-- SELECT SIMPLES
SELECT * FROM SUBSCRIPTION s WHERE S.SUBSCRIBER_ID = '5511970000017' AND PARTNER_ID = '3';

-- SELECT GROUP BY E VARIACOES
SELECT PARTNER_ID, count(*) FROM SUBSCRIPTION s GROUP BY PARTNER_ID HAVING count(*) > 2;

-- MAX OVER
SELECT max(s.PARTNER_ID) OVER (PARTITION BY s.SUBSCRIBER_ID) max_partner_id, s.* FROM SUBSCRIPTION s ;

SELECT * FROM (
SELECT max(s.PARTNER_ID) OVER (PARTITION BY s.SUBSCRIBER_ID) max_partner_id, s.* FROM SUBSCRIPTION s)
WHERE max_partner_id = partner_id;

-- SELECT ROUNUM, ROWID
SELECT rownum, rowid, s.* FROM SUBSCRIPTION s WHERE SUBSCRIPTION_ID = '1ac045da-1405-4e78-ab99-cenario15';
SELECT rownum, rowid, s.* FROM SUBSCRIPTION s WHERE rowid = 'AACFyYAAEAAAFs7AAD';



-- Join chato (mais dificil)
SELECT * FROM SUBSCRIPTION s
INNER JOIN SUBSCRIPTON_CHARGING_CONTROL scc 
ON S.SUBSCRIBER_ID = SCC.SUBSCRIBER_ID;

-- Join mais facil
SELECT * FROM SUBSCRIPTION s, SUBSCRIPTON_CHARGING_CONTROL scc 
WHERE s.SUBSCRIBER_ID = scc.SUBSCRIBER_ID;

-- rigth join
SELECT * FROM SUBSCRIPTION s, SUBSCRIPTON_CHARGING_CONTROL scc 
WHERE s.SUBSCRIBER_ID = scc.SUBSCRIBER_ID(+);

-- left join
SELECT * FROM SUBSCRIPTION s, SUBSCRIPTON_CHARGING_CONTROL scc 
WHERE s.SUBSCRIBER_ID(+) = scc.SUBSCRIBER_ID
AND s.PARTNER_ID(+) = scc.PARTNER_ID;

-- full outer join
SELECT * FROM SUBSCRIPTION s, SUBSCRIPTON_CHARGING_CONTROL scc 
WHERE s.SUBSCRIBER_ID = scc.SUBSCRIBER_ID(+)
UNION 
SELECT * FROM SUBSCRIPTION s, SUBSCRIPTON_CHARGING_CONTROL scc 
WHERE s.SUBSCRIBER_ID(+) = scc.SUBSCRIBER_ID;

-- Hash join - full nas duas tabelas
SELECT * FROM SUBSCRIPTION s, SUBSCRIPTON_CHARGING_CONTROL scc 
WHERE s.SUBSCRIBER_ID = scc.SUBSCRIBER_ID;

SELECT * FROM SUBSCRIPTION_ACTIVATION_CTRL;

-- Merge join - Acesso por index
SELECT /*+ full(s) full(scc) full(sac) */ * FROM SUBSCRIPTION s, SUBSCRIPTON_CHARGING_CONTROL scc, SUBSCRIPTION_ACTIVATION_CTRL sac 
WHERE s.SUBSCRIBER_ID = scc.SUBSCRIBER_ID
AND s.PARTNER_ID = scc.PARTNER_ID 
AND s.SUBSCRIBER_ID = sac.SUBSCRIBER_ID
AND s.SUBSCRIPTION_ID = sac.SUBSCRIPTION_ID 
AND scc.SUBSCRIBER_ID = sac.SUBSCRIBER_ID
AND s.SUBSCRIBER_ID IN  ('5511970000017');

-- nested loops - 1 acesso por index e outro n�o
SELECT * FROM SUBSCRIPTION s, SUBSCRIPTON_CHARGING_CONTROL scc
WHERE s.SUBSCRIBER_ID = scc.SUBSCRIBER_ID
AND s.PARTNER_ID = s.PARTNER_ID 
AND s.ACTIVATION_DATE <= SYSDATE - 360
AND s.SUBSCRIBER_ID IN  ('5511970000017')
AND s.PARTNER_ID = '3';


SELECT * FROM SUBSCRIPTION s WHERE NOT EXISTS (SELECT 1 FROM SUBSCRIPTON_CHARGING_CONTROL scc WHERE scc.SUBSCRIBER_ID = s.SUBSCRIBER_ID);

SELECT * FROM SUBSCRIPTION s WHERE SUBSCRIBER_ID IN (SELECT SUBSCRIBER_ID FROM SUBSCRIPTON_CHARGING_CONTROL scc);

SELECT * FROM SUBSCRIPTON_CHARGING_CONTROL WHERE SUBSCRIBER_ID = '5511970000016';


SELECT * FROM SUBSCRIPTION_TESTE;


SELECT S.SUBSCRIBER_ID, S.PARTNER_ID, S.SUBSCRIPTION_ID AS SUBSCRIPITION_ID, PARTNER_CHARGE_TOKEN FROM SUBSCRIPTION S
      WHERE 
      S.PARTNER_ID = 3
      AND S.ACTIVATION_STATUS = 1
      AND S.SUBSCRIPTION_TYPE = 0
      AND S.STATUS <> 0
      AND NOT EXISTS (
        SELECT 1 
        FROM SUBSCRIPTON_CHARGING_CONTROL SCC
        WHERE SCC.SUBSCRIBER_ID = S.SUBSCRIBER_ID
        AND SCC.PARTNER_ID = S.PARTNER_ID
      )
